version: '3'

services:
  iotown_message_parser:
    image: iotown_message_parser
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "local"
    env_file:
      - .env
    volumes:
      - ./parser:/root/
    command: python3 -u run.py --url ${IOTOWN_URL} --redis_url redis://redis --dry ${DRY_RUN:-'0'}

  redis:
    image: redis:7.0.5-alpine
    restart: always
    logging:
      driver: "local"
    volumes:
      - ./redis-data:/data
